### ISSUE TITLE
Add Conditional Schemas

### ISSUE THREAD

**Issue by AleksejDix** [formvuelate/formvuelate#129]
It is very common that input has a conditional relationship to another field. 

Problem: Currently it is very tedious to create large forms which have a tree form (not linear like a wizard form) 

Idea: To have a condition property on the schema object wich will be executed when the form model changes. Schema will be a computed property of the form model

**Comment by marina-mosti** [comment]
Hello @AleksejDix this can be accomplished with Formvuelate by making your schema a computed property, any object or array passed into the `schema` property of `SchemaForm` is reactive and will modify the form at runtime

**Comment by AleksejDix** [comment]
yes this is true, i wrote a similar lib in my company,

conditional schemas feel  like a very manuell  process which can be automated 


 ```js
const model = ref({
  gender: true
})


const schema = computed(() => ({
  gender: {
    component: 'Switch'
  },
 male: {
    condition: model => !!model.gender,
    component: 'Input'
  },
  female: {
    condition: model => !model.gender,
    component: 'Input'
  }
}))
```

**Comment by shentao** [comment]
I actually like the idea! Also nice seeing you again mate!

**Comment by marina-mosti** [comment]
Sounds interesting, will put it on the todo log :) Thanks for the idea

**Comment by AleksejDix** [comment]
i have a working demo for vue 2 now need to make it work for vue 3
