### ISSUE TITLE
Computed schemas lose reactivity with the plugin system

### ISSUE THREAD

**Issue by D3m1urg0** [formvuelate/formvuelate#141]
**Describe the bug**
When reproducing this example: https://formvuelate.js.org/#schemaform-with-v-model
with an Array-schema as the value changes computed property is updated (i can see that in devtools) but the rendered form is untouched

**To Reproduce**
try to use the following computed schema in the vmodel conditional-schema example 
https://github.com/formvuelate/formvuelate/blob/main/.vitepress/docs/components/ExampleVModel.vue
```
const schema = computed(() => {
      return formData.value.type === "A"
        ? [
            {
              component: "form-select", //FormText,
              label: "Schema A or B?",
              options: ["A", "B"],
              model: "type"
            },
            {
              component: "form-text",
              label: "A field",
              model: "aField"
            }
          ]
        : [
            {
              component: "form-select", //FormText,
              label: "Schema A or B?",
              options: ["A", "B"],
              model: "type"
            },
            {
              component: "form-text",
              label: "b field",
              model: "bField"
            }
          ];
    });
```
try changing the value of the select

**Expected behavior**
The A field mutates in B field on screen

**System Info**
- FormVueLate version:  2.0.0

**Additional context**

**Comment by marina-mosti** [comment]
Thanks for opening the issue @D3m1urg0 I'll take a look next week hopefully

**Comment by marina-mosti** [comment]
Hey @D3m1urg0 I've managed to set up using your example and it works fine on my end.

```html
<template>
  <div id="app">
    <SchemaForm :schema="schema" v-model="form" />

    <pre>{{ form }}</pre>
  </div>
</template>

<script>
import FormText from './components/FormText.vue'
import FormSelect from './components/FormSelect.vue'
// import FormCheckbox from './components/FormCheckbox.vue'
import { SchemaForm } from 'formvuelate'
import { ref, markRaw, computed } from 'vue'

markRaw(FormSelect)
markRaw(FormText)

export default {
  name: 'App',
  components: { SchemaForm },
  setup () {
    const form = ref({
      type: 'A',
      aField: '',
      bField: ''
    })

    const schema = computed(() => {
      return form.value.type === "A"
        ? [
          {
            component: FormSelect,
            label: "Schema A or B?",
            options: ["A", "B"],
            model: "type"
          },
          {
            component: FormText,
            label: "A field",
            model: "aField"
          }
        ]
        : [
          {
            component: FormSelect,
            label: "Schema A or B?",
            options: ["A", "B"],
            model: "type"
          },
          {
            component: FormText,
            label: "b field",
            model: "bField"
          }
        ];
    });

    return {
      form,
      schema
    }
  }
}
</script>
```

Can you check the above code and provide more info if needed?

**Comment by marina-mosti** [comment]
![Jan-08-2021 14-10-43](https://user-images.githubusercontent.com/14843771/104024635-5616c880-51bb-11eb-855a-4f0a26d4b637.gif)

**Comment by D3m1urg0** [comment]
That's unexpected !
I will try use your exact code in my enviornment and will give you some news about it.

in the meantime I thank you infinitely for this very useful library ;)

**Comment by D3m1urg0** [comment]
@marina-mosti i tested your code in my enviornment and it worked like expected (except for preventing model cleanup on schema changing without the prop set to true, but that could be related to my custom fields and is an offtopic behaviour)

then i edited step by step your model with my configuration and i found the last step before reactivity shouted:

```
<template>
  <div id="app">
    <SchemaForm :schema="schema" v-model="form" />
    <pre>{{ form }}</pre>
  </div>
</template>

<script>
import { ref, markRaw, computed } from "vue";
import { SchemaFormFactory } from "formvuelate";
import FormText from " ./components/FormText.vue";
import FormSelect from "./components/FormSelect.vue";

// import VeeValidatePlugin from "@formvuelate/plugin-vee-validate";  
// import LookupPlugin from "@formvuelate/plugin-lookup";

const SchemaFormWithPlugins = SchemaFormFactory([

//////////////* If i enable any of these 2 (also without options) the reactivity stops working *///////////////////

  // LookupPlugin({
  // }),
  // VeeValidatePlugin({
  // })
]);

markRaw(FormSelect);
markRaw(FormText);

export default {
  name: "App",
  components: { SchemaForm: SchemaFormWithPlugins },
  setup() {
    const form = ref({
      type: "A",
      aField: "",
      bField: ""
    });

    const schema = computed(() => {
      return form.value.type === "A"
        ? [
            {
              component: FormSelect,
              label: "Schema A or B?",
              options: ["A", "B"],
              model: "type"
            },
            {
              component: FormText,
              label: "A field",
              model: "aField"
            }
          ]
        : [
            {
              component: FormSelect,
              label: "Schema A or B?",
              options: ["A", "B"],
              model: "type"
            },
            {
              component: FormText,
              label: "b field",
              model: "bField"
            }
          ];
    });

    return {
      form,
      schema
    };
  }
};
</script>

```

then this seems to be related to the plugins (both of them)
should I open the issue in the related projects?

**Comment by marina-mosti** [comment]
Interesting. No need to open issues on the plugins, ill investigate thank you @D3m1urg0

**Comment by marina-mosti** [comment]
> //////////////* If i enable any of these 2 (also without options) the reactivity stops working *///////////////////

  // LookupPlugin({
  // }),
  // VeeValidatePlugin({
  // })

@D3m1urg0 both these plugins require configuration. Can you provide a minimal working reproduction on a repo of the code, so that I can see the actual errors youre getting?

**Comment by D3m1urg0** [comment]
@marina-mosti
i really suck at Github so i am sure there's a better way to share this...

Actually this is my "sandbox vue 3 test" repo, in which I am adding all the best libraries I find online, (and your is definitely one of them)
i made it public and created a branch with the working example of this issue.

I don't know if there's an easier / cleaner way to provide you the reproduction,. i hope this will help.

in src/pages you can find "index.vue":  this is my original form (globally registered with plugins in src/plugins/formvuelate.js)
there's also "workingFormVuelate.vue", that's the one i copy pasted up there to provide the step in which everything stops working.

https://github.com/D3m1urg0/ainulindale/tree/formvuelate-inspect-bug

If i can do something to help you just ask, i will try my best.

**Comment by D3m1urg0** [comment]
@marina-mosti i did this that's probably better for inspecting the issue:

https://codesandbox.io/s/test-reactivity-formvuelate-rpj1e?file=/src/App.vue

**Comment by marina-mosti** [comment]
Thank you @D3m1urg0 this is super helpful, and exactly what I needed to investigate

**Comment by marina-mosti** [comment]
Hello @D3m1urg0 issue should be fixed, please update both your plugins to next version

**Comment by D3m1urg0** [comment]
> Hello @D3m1urg0 issue should be fixed, please update both your plugins to next version

Hi, i just updated dependencies in my sandbox 
https://codesandbox.io/s/test-reactivity-formvuelate-rpj1e?file=/src/App.vue

to  "@formvuelate/plugin-lookup": "1.2.1" & "@formvuelate/plugin-vee-validate": "1.0.5"
but nothing seems to be changed.
I gave you edit permission on the example itself, is there some other else i have to do other than update the dep?

**Comment by marina-mosti** [comment]
Hey @D3m1urg0, you're right something seems to break in the packaged version. Thanks for letting me know

**Comment by marina-mosti** [comment]
Hello again @D3m1urg0 
Issue should be fixed. Codesandbox isnt finding the new 1.2.3 version for lookup yet though. 
Let me know if you run into further issue

**Comment by D3m1urg0** [comment]
Hi @marina-mosti,
the reactivity is restored, but it created a new unexpected behaviour.

You can reproduce it directly in the codesandbox i provided: (but i get the same result also on my local project)
if you insert any value inside the textfields they will loose the focus at each input event (you can just type one letter then you need to select the field again)

I tested it also commenting the plugins options and everything works as intended then it should be some kind of regression from the last fix.

**Comment by marina-mosti** [comment]
Going to close this issue and open a new one to keep the issues separate
