### ISSUE TITLE
Documentation of component registration

### ISSUE THREAD

**Issue by wiese** [formvuelate/formvuelate#144]
In the [schema documentation](https://formvuelate.js.org/#prop-schema) about the `component` property it currently says (emphasis mine)
> You can use the name of the component as a String instead, for example 'FormText', but be aware that the component needs to either be imported globally, **or in your file** first.

As a consequence, I tried to register the custom components locally in my component using formvuelate's `SchemaForm` and identify the components to use by string (to get a green tick in the "code-free schema" column of my [decision matrix](https://twitter.com/pctgrass/status/1362354813472751620)) - which did not work.

This is somewhat expected (now) knowing that formvuelate merely is [using](https://github.com/formvuelate/formvuelate/blob/7ad4aebb2186521ff5dfe7d630108a1527a29f01/src/SchemaForm.vue#L20) vue's [`:is` special attribute](https://v3.vuejs.org/api/special-attributes.html#is) and that, per the [vue documentation](https://v3.vuejs.org/guide/component-registration.html#local-registration) (sic),

> locally registered components are not also available in subcomponents

in vue 3.

The [reference implementation](https://github.com/marina-mosti/dynamic-schema-vuelidate/blob/ca02778998ea2555b25efe84945dacd46195bc19/src/main.js#L12) featured in e.g. the "Validating Schema-Driven forms with Vuelidate" [blog post](https://www.vuemastery.com/blog/Validating-Schema-Driven-forms-with-Vuelidate/) also uses global registration.

So maybe the documentation should just suggest global registration. Or is there another way I'm missing?

**Comment by marina-mosti** [comment]
@wiese thanks for the issue. You're actually right, this is an oversight. We've opened a discussion around this and there seems to be a few ways we can resolve this, most likely through the SchemaFormFactory by injecting the list of components into it.

Hopefully, I can get it done soon :)

**Comment by marina-mosti** [comment]
I've gone ahead and corrected/removed this bit from the docs until its addressed

**Comment by marina-mosti** [comment]
@wiese ability to register local components has been added on `v1.2.0` with #145 
[SchemaFormFactory docs](https://formvuelate.js.org/#using-locally-imported-components)

**Comment by marina-mosti** [comment]
Codesandbox with example for reference: https://codesandbox.io/s/fvl-local-imports-48y8y

**Comment by wiese** [comment]
Thank you very much. The [documentation](https://formvuelate.js.org/#using-locally-imported-components) looks awesome!
