### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by timsayshey** [formvuelate/formvuelate#152]
Does this package have Typescript support or are you planning to add it?

When trying to use this in my Vue 3 app using Typescript I get the following error:
```
Could not find a declaration file for module 'formvuelate'. '.../node_modules/formvuelate/dist/formvuelate.common.js' 
implicitly has an 'any' type.
  Try `npm i --save-dev @types/formvuelate` if it exists or add a new declaration (.d.ts) file containing 
`declare module 'formvuelate';`Vetur(7016)
  ```

**Comment by marina-mosti** [comment]
We don’t have definitions yet. I’m not sure when we will add them, I’ve been working on version 3.x which I should release soon.

After that there’s other features I want to address before this. Feel free to make a PR :)

**Comment by timsayshey** [comment]
Good to know - Thanks!
