### ISSUE TITLE
How to use with nuxt and Vue2

### ISSUE THREAD

**Issue by bhumit070** [formvuelate/formvuelate#164]
Hey there I want to generate forms throught schema and I wanted to know
how to use this package in nuxt js and vue 2 I have read through docs but did not find anything 
so it would be great to get help from here

**Comment by marina-mosti** [comment]
Hello @bhumit070 FormVueLate is a Vue 3 library. There's no current real support for Vue 2, and no immediate plans for backwards compatibility

**Comment by bhumit070** [comment]
Okay thanks for reply

**Comment by zach-at-healthpilot** [comment]
Maybe ... you ... should .. consider ... PUTTING THAT IN THE DOCUMENTATION.
