### ISSUE TITLE
Default values for fields?

### ISSUE THREAD

**Issue by hognevevle** [formvuelate/formvuelate#166]
Hello!

This is probably a stupid question, but I can't seem to figure out how I can set a default value for my form fields. Can you provide an example on how to achieve this?

**Comment by hognevevle** [comment]
Never mind :) 

```
const form = ref({
      firstName: "My default value here"
    });

useSchemaForm(form);
```

**Comment by marina-mosti** [comment]
Hey @hognevevle , yep you got it.
This gives me an idea for adding a proposed value to the schema to inject a default value so I'm going to reopen this as a reminder.
