### ISSUE TITLE
docs: `validation.touched` should be `validation.meta.touched`

### ISSUE THREAD

**Issue by hognevevle** [formvuelate/formvuelate#168]
**Describe the bug**
From the last example at https://formvuelate.js.org/guide/veevalidate.html#component-requirements :
```
    <span v-if="validation.touched">{{ validation.errorMessage }}</span>
```

.. is incorrect. Instead, it should be: 
```
    <span v-if="validation.meta.touched">{{ validation.errorMessage }}</span>
```

**Comment by logaretm** [comment]
You are right, sorry about that. This is fixed in #170 which should be merged and updated soon
