### ISSUE TITLE
Array form fields

### ISSUE THREAD

**Issue by hognevevle** [formvuelate/formvuelate#169]
When using a component that emits a model value with an array of strings (multi-select), the following error is thrown:

```
[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected String, Number, got Array 
  at <WithFieldWrapper key=0 component= {name: "withFieldWrapper", props: {…}, __props: Array(2), __emits: null, setup: ƒ, …} label="Brands"  ... > 
  at <SchemaField key="brands" field=
...
```

How can I indicate that I do actually expect this to be an array?

**Comment by marina-mosti** [comment]
Hello. Please provide some example code and a minimal reproduction of the bug so I can look at it

**Comment by hognevevle** [comment]
Thanks Marina,

You'll find a reproduction here: https://github.com/hognevevle/headlessui-bug/tree/formvuelate
(in the formvuelate branch)

I've just overridden the update method here, so it emits an array instead of just the regular text. When typing something in one of the inputs, you'll see the error in the console.

**Comment by marina-mosti** [comment]
Hey @logaretm seems the problem here is with the `vee` plugin. On line 118 you are setting the type to strict `[String, Number]`.

Is there a reason why vee needs these strict types or can we remove typing here?

**Comment by logaretm** [comment]
Yea, I'm not sure why I have that there but it is safe to remove. I created a PR for it.
