### ISSUE TITLE
In the playground where is the work part?

### ISSUE THREAD

**Issue by erkage** [formvuelate/formvuelate#181]
On the codesandbox playground (fvl-playground-3x) there is a "work" part both in Object and Array schema but it not appears anywhere on the "rendered" side. Do i miss something? Is it intended?

**Comment by marina-mosti** [comment]
Not sure I understand what the problem is. Can you provide a screenshot or example?

**Comment by erkage** [comment]
Here:
[https://codesandbox.io/s/fvl-playground-3x-ojbt9?from-embed=&file=/src/App.vue:2053-2746](https://codesandbox.io/s/fvl-playground-3x-ojbt9?from-embed=&file=/src/App.vue:2053-2746)
what is the highlighted/selected part for? It's not processed/rendered/showed anywhere as i can see!?

**Comment by marina-mosti** [comment]
Thanks @erkage I've gone ahead and fixed it, it was a problem with how the `SchemaForm` component was getting registered. Its a bit of a hack since we need it to be from a JSON string parsed schema, but its now working 👌🏻
