### ISSUE TITLE
Field props are not reactive

### ISSUE THREAD

**Issue by pau-santesmasses** [formvuelate/formvuelate#195]
**Describe the bug**
The props that are passed to the field components (i.e. FormText) lose their reactivity.

**To Reproduce**
Make a schema with at least one reactive property. For instance:

```
const myRef = ref('initial label')

const schema =  {
   myField: {
    component: FormText,
    label: myRef
  }
}

setTimeout(() => myRef.value = 'updated label', 1000)
```

**Expected behavior**
The FormText component should receive a reactive `label` prop. In this case it would get updated to the new value after 1s.

**System Info**
- FormVueLate version: 3.1.1
- plugins being used with versions:

**Additional context**
I think the issue lies in how the SchemaField props get destructured into the `binds` object, losing the reactivity.
I spent some time with it but I could not find an easy fix.

![stale binds](https://user-images.githubusercontent.com/59452992/123284965-a7e9ab80-d4da-11eb-9981-5967c0f95ab5.png)

**Comment by marina-mosti** [comment]
Hey @pau-santesmasses thanks for the bug report, ill look into it as soon as i get a chance
