### ISSUE TITLE
Using vue-i18n in scheme

### ISSUE THREAD

**Issue by erkage** [formvuelate/formvuelate#199]
What do you think is it possible to achive that (in the current version) for example the labels changeing when i switch the language in the i18n switcher?

In my first try the initial load is working, so default language is EN and using the vue-i18n's `t` function in scheme's label property it loads the correct translation. But when i switch the language nothing happens.
I have ideas why not but before i getting deep into it i'd like to ask you that what's your opinion it has a possibility to get it work?

My scheme:

```
const formSchema = {
  email: {
    component: FormText,
    label: i18n.global.t("login.email"), //initialy loads "E-mail address" for label
  },
  password: {
    component: FormText,
    label: i18n.global.t("login.pw"), //initialy loads "Password" for label
  }
}
```

**Comment by marina-mosti** [comment]
Should probably use a computed for the schema so that the internationalization is reactive

**Comment by erkage** [comment]
Great idea!

But i tried it this way:
```
<template>
  {{ i18n.global.t("login.email") }}
  <SchemaForm :schema="formSchema" />
</template>
```
```
...

markRaw(FormText);

const formSchema = computed(() => {
  return {
    email: {
      component: FormText,
      label: i18n.global.t("login.email"),
    },
    password: {
      component: FormText,
      label: i18n.global.t("login.pw"),
    }
  }
};

const formData = ref({});
useSchemaForm(formData);
```

and in the template it reacted to the language change but the labels aren't 🙁 .

**Comment by marina-mosti** [comment]
Make sure you are using the latest version of FVL since I fixed a reactivity bug recently. I dont know the inner workings of i18n but if it triggers the computed property it should change the schema, and thus your label prop binding

**Comment by erkage** [comment]
Yaaay! Works like a charm! I was on 3.2.0 😉.
Thank you very much!

/* just bought some trees 😉 */

**Comment by marina-mosti** [comment]
Thanks for the 🌲:D
