### ISSUE TITLE
The `config` property does nothing

### ISSUE THREAD

**Issue by andersevenrud** [formvuelate/formvuelate#201]
**Describe the bug**

The `config` property does nothing. Example:

```json
{
  "email": {
    "component": "FormText",
    "label": "Your email",
    "required": true,
    "config": {
      "type": "email"
    }
  },
}
```

**To Reproduce**

1. Go to the playground: https://codesandbox.io/s/fvl-playground-3x-ojbt9?from-embed=&file=/src/App.vue:2989-2995
2. Open devtools
3. Inspect the email field
4. Notice that the `type` is wrong on the DOM element.

**Expected behavior**

The `type` should be set to `email` on the DOM element.

**System Info**
- FormVueLate version: v3.2.2
- plugins being used with versions: none

**Comment by marina-mosti** [comment]
I'm not sure what this `config` is, but just put the type at the root level where the label and required are.
Everything on that level is bound to the component that it instantiates

Unless your own component has a config property that then you use to sort out these configuration params, but thats beyond the scope of the lib and more on the side of your component composition

**Comment by andersevenrud** [comment]
Aha! Thank you very much for solving this issue and excellent response time :blush:
