### ISSUE TITLE
Feature request: Custom `<form>` attributes

### ISSUE THREAD

**Issue by andersevenrud** [formvuelate/formvuelate#203]
**Is your feature request related to a problem? Please describe.**

I've encountered a situation where I need custom attributes on the `<form>` element. More specifically `novalidate` in order to disable the browsers validation (and its popups).

**Describe the solution you'd like**

Something like this would be nice:

```vue
<SchemaForm
  :schema-form-attributes="{ foo: 'bar' }"
  :schema="mySchema"
/>
```

**Describe alternatives you've considered**

Maybe a slot ?

```vue
<SchemaForm
  :schema="mySchema"
>
  <template #formWrapper="attrs">
    <form v-bind="attrs" novalidate>
      <slot />
    </form>
  </template>
</SchemaForm>
```

Or a custom defined element that is used for `:as` internally ?

```vue
<SchemaForm
  schema-form-element="MyCustomForm"
  :schema="mySchema"
/>

<MyCustomForm>
    <form v-bind="$attrs" novalidate>
      <slot />
    </form>
</MyCustomForm>
```

**Comment by andersevenrud** [comment]
Just a note here, adding `@invalid.prevent` to a form field will disable the behavior on a per field basis, but this is not optimal. And AFAIK there's no way to use `sharedConfig` on `<SchemaForm>` to add events globally (because of the `v-on` Vue sugar).

**Comment by logaretm** [comment]
The `SchemaForm` should inherit the attributes and pass them over to the root element, doesn't this already work?

```vue
<SchemaForm :schema="schema" @submit="onSubmit" novalidate />
```

**Comment by andersevenrud** [comment]
Ah! I didn't try adding stuff to the `<SchemaForm>` :man_facepalming: Is this mentioned in the docs ? I was looking for some examples or tips regarding this... probably just me that totally missed something though.

Works like a charm. Thanks!
