### ISSUE TITLE
When a condition is not met maybe the schema row shouldn't be rendered aswell

### ISSUE THREAD

**Issue by erkage** [formvuelate/formvuelate#208]
So, in this case
```
...
something: {
  component: SchemaForm,
  schema: {
    ...
    condition: () => false
  }
}
...
```
A `div.schema-form` always be rendered with empty content. It's not break anything but when you add some css style for example padding it affects the layout.

It can be easily solve with some css in the internal elements but maybe it's totally unnecessary to render that empty `div.schema-form` and can be ommited.

**Comment by marina-mosti** [comment]
Hey @erkage, to be honest, I hadn't considered the possibility of conditioning the whole subschema, this will take some work so I'm going to label as it as an enhancement for now and will get back to it when I get some time. Thanks for the idea

**Comment by erkage** [comment]
I managed to solve the `padding` problem in my case with:
```
something: {
  component: SchemaForm,
  schema: {
    ...
  },
  condition: () => false
}
```
and added the `padding` style to the `div.schema-col`.
But i can imagine a case where this is not enough.
