### ISSUE TITLE
Vee-validate-plugin custom error messages

### ISSUE THREAD

**Issue by erkage** [formvuelate/formvuelate#209]
I read the docs about 5 times and can't figure out how to add custom error message texts to validations.

For example i have a required field:
```
<template>
  <SchemaFormWithValidation :schema="formSchema" />
</template>

<script setup>
...
  import {
    SchemaForm,
    useSchemaForm,
    SchemaFormFactory,
  } from "formvuelate";
  import VeeValidatePlugin from "@formvuelate/plugin-vee-validate";
...
  const SchemaFormWithValidation = SchemaFormFactory([
    VeeValidatePlugin({}) 
  ]);
...
  const formSchema = {
    requiredField: {
      component: FormText,
      label: "a required filed",
      validations: "required",
    },
  }
...
</script>
```

And in the `validation.errorMessage` i got `requiredField is not valid`.

I also have a `@vee-validate/i18n` compatible json file that i happily use here if possible 🙂 .

**Comment by logaretm** [comment]
You would need to [follow vee-validate's instructions there](https://vee-validate.logaretm.com/v4/guide/i18n#using-vee-validatei18n). You can use your own JSON similarly.

**Comment by erkage** [comment]
@logaretm Ahh, i tried it before but didn't know that `configure()` also needed here. Tried to add the `generateMessage` with `localize` to `VeeValidatePlugin()`. I know it's not mentioned in the docs but somehow it makes sense to me 🙂 . 
Now it works like charm. Thank you!

**Comment by erkage** [comment]
However maybe a note line in the docs can mentioned this. What do you think?

**Comment by erkage** [comment]
@logaretm I have a related question if you don't mind. Now on load i have the correct locale string for errors. But i can't figure out how to change the locale after it (without reloading page). 
[Here](https://github.com/logaretm/vee-validate/issues/3130) i see that is intended but can't find how can i 're-trigger validation' here!?

Also trying with `setLocale` from `@vee-validate/i18n` but with no luck.

The code is the same as above extended `vee-validate` and `@vee-validate/i18n`

**Comment by logaretm** [comment]
No way at the moment to access the validation API from FormVuelate, we are discussing it here #204 

Personally, I prefer to reload the page whenever a locale changes. I don't see a benefit to changing the locale "in-place" for most web apps

**Comment by erkage** [comment]
@logaretm 
Oh no! Now i have to rethink my concept. 🙂 

I like "streamline experience" so reloading is never an option for me (if yes it's a sign of a problem/bug).

I'm working on a small multilangual questionnaire (and as a base form handling for my future projects) and when started the work i was thinking a lot about that should i ask the preferred language in first place and the move on but than i settled that why the user can't change mind during the questionnaire. For example i prefer english all the time but what if i can't clearly understand the 10th question, for example it's a legal expression, and then i like to change language to my mother tongue without losing my progress or anything.
Yeah i know it's an edge case but i always think that if something can happen once i have to deal with and make the best from it.

Thank you for your answer!
