### ISSUE TITLE
Support async components

### ISSUE THREAD

**Issue by hognevevle** [formvuelate/formvuelate#211]
Now that async components are starting to be more supported in Vue through [Suspense](https://v3.vuejs.org/guide/migration/suspense.html), it would be great to be able to use such components together with formvuelate (i.e. components with an async setup function). 

Currently this does not seem to be supported. Let me know if you'd like me to provide an example.

**Comment by marina-mosti** [comment]
Hey @hognevevle yeah, please provide a repro

**Comment by marina-mosti** [comment]
Hey @hognevevle did you manage to reproduce? Or did you find a way to clear your issue?

**Comment by hognevevle** [comment]
Hey Marina, we chose to ditch Suspense in this specific scenario for now. I will reopen as soon as I can find time to put together a repro.
