### ISSUE TITLE
Field lookup does not work in nested schemas

### ISSUE THREAD

**Issue by datenspast** [formvuelate/formvuelate#224]
First of all: Thanks for the great library!
Not sure if this is a bug that relates to the formvuelate library or the lookup plugin. 
Maybe the bug relates to different problems. I name them [A] and [B].

**Describe the bug**
It seems that the field lookup does not work in nested schemas.

**To Reproduce**
[A]
I modified the codepen example here:
https://codesandbox.io/s/fvl-nested-schema-3-x-forked-tq9zl?file=/src/App.vue
You can uncomment/comment the lines 40 and 41 to reproduce it.

**Expected behavior**
I would expect that the following would work as well, but the field in the nested schema is not rendered.
I`m also refering to the example in the guide for nested schemas: https://formvuelate.js.org/guide/lookup.html#nested-schema-caveats
```js
const SchemaFormWithPlugins = SchemaFormFactory([
    LookupPlugin({
        mapComponents: {
          Text: FormText,
        }
    })
])

const SCHEMA = [
  {
    model: "firstName",
    component: "Text",
    label: "First Name",
  },
  {
    model: "nested",
    component: SchemaForm,
    schema: [
      {
        model: "nestedfirstName",
        component: FormText, // this works
        // component: "Text", // this does not work
        label: "First Name nested",
      },
    ],
  },
]
```
[B]
Please note that the solution to `mapComponent` in the `SchemaFormFactory` described here https://formvuelate.js.org/guide/lookup.html#nested-schema-caveats did not work in my case.

If this is applied, it seems that the nested schema is not rendered at all:
https://codesandbox.io/s/fvl-nested-schema-3-x-forked-s3s50?file=/src/App.vue
```js
const SchemaFormWithPlugins = SchemaFormFactory([
  LookupPlugin({
    mapComponents: {
      SchemaForm: "SchemaFormWithPlugins",
      Text: FormText,
    },
  }),
]);

const SCHEMA = [
  {
    model: "firstName",
    component: "Text",
    label: "First Name",
  },
  {
    model: "nested",
    component: SchemaForm, // this works
    // component: "SchemaForm", // this does not work
    schema: [
      {
        model: "nestedfirstName",
        component: FormText, 
        label: "First Name nested",
      },
    ],
  },
];
```

**System Info**
- Formvuelate version: 3.1.0
- plugins being used with versions:
```js
"@formvuelate/plugin-lookup": "^2.1.0",
"@formvuelate/plugin-vee-validate": "^2.2.1",
```

Thanks for any help!

**Comment by marina-mosti** [comment]
Hey @datenspast thanks I'm on vacation I'll check it out when I get back 👍

**Comment by marina-mosti** [comment]
Hey @datenspast try changing the `component: SchemaForm, // this works` for `component: SchemaFormWithPlugins,` since each level of the nested schema needs to have access to the plugin implementation

https://codesandbox.io/s/fvl-nested-schema-3-x-forked-r16hz?file=/src/App.vue:869-906

Is that what you were expecting?

**Comment by datenspast** [comment]
Hi @marina-mosti : Many thanks for your reply and support!
Your proposed solution works but does not solve the issue I´m facing.
Since we get the Schema from an API all values are Strings. So we get e.g. 
```js
{
    model: "firstName",
    component: "Text",
    label: "First Name",
  },
  {
    model: "nested",
    component: "SchemaForm", // we get this as a String
    schema: [
      {
        model: "nestedfirstName",
        component: "Text", // we get this as a String
        label: "First Name nested",
      },
    ],
  },
```
I understand the guide (https://formvuelate.js.org/guide/lookup.html#nested-schema-caveats) that it is also possible to use Strings and map them to the component (SchemaFromWithPlugins in my case):
```js
{
  "firstName": {
    "component": "string",
    "info": "First Name"
  },
  "work": {
    "component": "SchemaForm",
    "schema": {
      "address": {
        "type": "FormText",
        "label": "Work address"
      },
      "details": {
        "component": "SchemaForm",
        "schema": {
          "position": {
            "type": "FormText",
            "label": "Work position"
          }
        }
      }
    }
  }
}

// Note "SchemaFormWithPlugin" getting remapped

const SchemaFormWithPlugin = SchemaFormFactory([
  LookupPlugin({
      SchemaForm: 'SchemaFormWithPlugin', // is the "mapComponents" not included by intention here? I tried it this way but it did not work as well.
      [...]
    }
  })
])
```

**Comment by marina-mosti** [comment]
@datenspast are you importing components globally? or locally into this file?

Did you check out this caveat: https://formvuelate.js.org/guide/plugins.html#using-locally-imported-components ?

**Comment by marina-mosti** [comment]
Additionally:
`component: "SchemaForm", // we get this as a String`

You're going to have to parse this

**Comment by marina-mosti** [comment]
So:
`SchemaForm: "SchemaFormWithPlugins",`

This inside `mapComponents` can not work, because the component `SchemaFormWithPlugins` is not globally registered or passed down the schema tree.
Its literally a constant inside your component, so subcomponents have no way of knowing about it.

`SchemaFormFactory` takes a second param `components` that registers components in child schema forms or nested schemas. The problem here is that you cant really make the factory a child of itself 😓 

I don't see right now any other way of solving this other than you doing a pre-lookup-plugin parsing of the internal `schema.component` properties into the name of your constant before you feed it your `schema`.

I'm honestly trying to remember how it worked when I wrote this piece of docs, but ill do more research and try to figure it out and/or delete the documentation which is misleading.

PS: Didnt mean to close, reopening :)

**Comment by datenspast** [comment]
> @datenspast are you importing components globally? or locally into this file?

I`m importing components locally into this file. 
> Did you check out this caveat: https://formvuelate.js.org/guide/plugins.html#using-locally-imported-components ?

I tried to make some changes based on this, but did not manage to solve the issue.
>I don't see right now any other way of solving this other than you doing a pre-lookup-plugin parsing of the internal 
schema.component properties into the name of your constant before you feed it your schema.

Yes, that approach seems to work. I tried this here:
https://codesandbox.io/s/fvl-nested-schema-3-x-forked-c05qr?file=/src/App.vue

@marina-mosti : Many thanks for addressing this issue by adding it as a new feature into the library.

**Comment by datenspast** [comment]
Hi @logaretm and @marina-mosti!

I am really sorry to bug you again but the new Feature does not seem to work if the `VeeValidatePlugin` is also used.
Or do I miss anything?

```js
const SchemaFormWithPlugins = SchemaFormFactory([
  LookupPlugin({
    mapComponents: {
      Text: FormText,
    },
  }),
  // if this is included, the nested schema is not displayed.
  VeeValidatePlugin({        
    }),
]);

const SCHEMA = [
  {
    model: "firstName",
    component: "Text",
    label: "First Name",
  },
  {
    model: "nested",
    component: "SchemaForm",
    schema: [
      {
        model: "nestedfirstName",
        component: "Text", // does not work
        // component: FormText, // Works if VeeValidatePlugin is included
        label: "First Name nested",
      },
    ],
  },
];
```
Please find an example here:
https://codesandbox.io/s/fvl-nested-schema-3-x-forked-5o1jt?file=/src/App.vue

Many thanks again for your help (I owe you a forest...)

**Comment by marina-mosti** [comment]
Thanks for the repro @datenspast 

@logaretm i have a feeling somewhere around ln 58-64 were conflicting in the parsing bc on ParsedSchema  ln 104 I need a way to identify the name. I guess maybe we could try changing that condition to check for a `.schema` also.
Wdyt?
