### ISSUE TITLE
Model cleanup on schema change does not work with nested schema

### ISSUE THREAD

**Issue by victorlambert** [formvuelate/formvuelate#227]
**Describe the bug**
When nested schema with conditions are used, model cleanup on schema change throw this error : 
`Cannot read property 'split' of undefined
`
**To Reproduce**
1. Create a nested schema with preventModelCleanupOnSchemaChange on true
2. Use condition property to conditionally display a field
3. Fulfil condition, the field display correctly
4. Unfulfil condition, formvuelate try to cleanup model and throw an error

**Expected behavior**
The field should disappear with model cleanup

**System Info**
- FormVueLate version: 3.5.0
- plugins being used with versions: 
@formvuelate/plugin-vee-validate: 3.4.0
vee-validate : 4.4.9

**Additional context**
`findNestedFormModelProp ` expect formModel on first param
https://github.com/formvuelate/formvuelate/blob/c6dca75640a3d8c88d690d82da422cd3173c7953/packages/formvuelate/src/utils/Helpers.js#L18

And we do not provide it in `findNestedFormModelProp `
https://github.com/formvuelate/formvuelate/blob/c6dca75640a3d8c88d690d82da422cd3173c7953/packages/formvuelate/src/utils/Helpers.js#L44

**Comment by logaretm** [comment]
Which version of vee-validate (not the plugin) are you using?

**Comment by victorlambert** [comment]
I'm using 4.4.9.
