### ISSUE TITLE
Locally imported components not working

### ISSUE THREAD

**Issue by arthur-alexander** [formvuelate/formvuelate#238]
**Describe the bug**
Locally imported components does not work as expected.  When declaring the component property as a string, nothing is being rendered in the browser.

I came across the discussion at issue [#144](https://github.com/formvuelate/formvuelate/issues/144). The included Codesandbox link works as expected. But if you upgrade formvuelate to the latest version the same thing happens. 

**Expected behavior**
When importing components locally and declaring the component property as a string, I'm expecting it to be rendered. 

**System Info**
- FormVueLate version: 3.6.1

**Additional context**
Here is a Codesandbox link illustrating the issue: https://codesandbox.io/s/fvl-local-imports-forked-2ez5q

**Comment by marina-mosti** [comment]
Thanks for reporting this @arthur-alexander

**Comment by marina-mosti** [comment]
Hey @arthur-alexander can you give it a shot with 3.6.2? Codesandbox isn't playing nice with 3.6.2 for me for some reason, keeps throwing 520s

**Comment by arthur-alexander** [comment]
Hi @marina-mosti. I've tested it with 3.6.2 and the same thing happens. No components are being rendered unfortunately.
