### ISSUE TITLE
Default values with value "false" are not added to model during initialisation

### ISSUE THREAD

**Issue by datenspast** [formvuelate/formvuelate#240]
**Describe the bug**
Default values with value "false" are not added to model during initialization.

**To Reproduce**
I added an example here: https://codesandbox.io/s/fvl-boolean-defaults-m714e?file=/src/App.vue
```js
const SCHEMA = [
  {
    model: "select_default_true",
    component: FormCheckbox,
    label: "Default is true",
    default: true,
  },
  {
    model: "select_default_false",
    component: FormCheckbox,
    label: "Default is false",
    default: false,
  },
];
```

**Expected behavior**
I would expect a model with the values:
```js
{
  "select_default_true": true,
  "select_default_false": false
}
```
but i get:
```js
{
  "select_default_true": true,
}
```

**System Info**
- FormVueLate version: 3.6.3
- plugins being used with versions: -

**Additional context**
Maybe the check for defaults has to be extended with something like `... || typeof(default==='boolean')`
By the way, thanks for the new feature with the defaults. This is very helpful and makes custom solutions obsolete.

**Comment by marina-mosti** [comment]
Hi @datenspast thanks for opening the issue, this really helps with real world proofing/building
