### ISSUE TITLE
Load schema from json source

### ISSUE THREAD

**Issue by wousser** [formvuelate/formvuelate#242]
Feature request or question

I'm trying to load the schema from an external source in valid JSON format. However, FormVueLate is using an invalid JSON schema for form generation.

Is there a way to convert to and from JSON, or is there a plan to make the scheme valid JSON?

Valid JSON
```
"schema": [
        {
          "component": "FormText",
          "label": "First Name",
          "model": "firstName"
        },
        {
          "component": "FormText",
          "label": "Last Name",
          "model": "lastName"
        }
]
```

Current schema used in FormVueLate:
```
const SCHEMA = [
  [
    {
      component: FormText,
      label: "First Name",
      model: "firstName",
      style: "margin-right: 10px",
    },
    {
      component: FormText,
      label: "Last Name",
      model: "lastName",
    },
  ],...
```

**Comment by marina-mosti** [comment]
Hi @wousser 

The schema that you're showing here is not "invalid JSON", it's JavaScript.
If you want to use a JSON schema, aka, components in string format you have to declare your components globally, or use `SchemaFormFactory` to inject them.

Please refer to the documentation on this, and the `Lookup` plugin for more control over how you construct/parse your custom schema into FVL format

**Comment by wousser** [comment]
Thanks for your quick answer. That will work. I overlooked the plugin section and thought the Lookup was a plugin to autocomplete locations.
