### ISSUE TITLE
custom element for form

### ISSUE THREAD

**Issue by danbars** [formvuelate/formvuelate#243]
**Is your feature request related to a problem? Please describe.**
Some libraries have a custom form element, such as QForm in Quasar and ElForm in ElementPlus.
This custom element creates certain behavior and affects its child input-fields, and also has custom attributes that you can add to it. When using these libraries it is important to use the custom form element and not a standard form tag

**Describe the solution you'd like**
I'd like to be able to define my own form wrapping tag. Possibly by using a special slot. Maybe something like:
```
<schema-form
    :schema="schema"
>
  <template slot="form">
    <q-form><slot></slot></q-form>
  </template>
</schema-form>
```

**Describe alternatives you've considered**
pass an attribute to SchemaForm to make it skip rendering of the form tag completely, and then the wrapping component can also create the form tag:
```
<q-form>
  <schema-form
    :schema="schema"
    :skipFormTag="true"
  />
</q-form>
```

**Comment by marina-mosti** [comment]
Hey @danbars sounds like a good idea, thank you, we'll do some analysis about the possibilities :)
