### ISSUE TITLE
Using  formvuelate  + vee-validate one_of rule

### ISSUE THREAD

**Issue by scramatte** [formvuelate/formvuelate#245]
Hello,

Can you give me an hand to get working vee-validate one_of ?
I'm using the following code. Validation is working well except "one_of" rule. I use it to check passwords are same before sign up. It looks that  "one_of" rule doesn't get  password current value. 

```
const userData = reactive({
  name: '',
  email: '',
  password: ''
});

const SCHEMA = {
  password: {
    component: 'FormText',
    type: 'password',
    placeholder: 'password',
    validations: { required, min: {length: 8}  },
  },
  confirmPassword: {
    component: 'FormText',
    type: 'password',
    placeholder: 'confirm-password',
    validations: { required, min: {length: 8}, one_of: userData.password  },
  },
};

useSchemaForm(userData);
const schema = computed(() => { return SCHEMA });

```

**Comment by scramatte** [comment]
Can you give me a sandbox to fork with formvuelate + vee-validate plugin?

**Comment by logaretm** [comment]
Are you sure you are using the[ `one_of` rule](https://vee-validate.logaretm.com/v4/guide/global-validators#one_of) correctly?

According to the vee-validate docs:

> The field under validation must have a value that is in the specified list. Uses double equals for checks.

Meaning you should pass a list to search in, not a string.

So this should work:

```
one_of: [userData.password]
```

**Comment by marina-mosti** [comment]
Closing since this is not a FVL issue :) Any further Q's about the `one_of` rule please address them in the vee-validate repo

**Comment by scramatte** [comment]
Hello, 

sorry  but I think that is related to Fvl...

As @logaretm told me I've put value between bracket and still doesn't works because when you define schema validations  one_of  value is not reactive. 

Please send me a link to sandbox.io with  fvl+vee-validate plugin and I prepare you an example.

Regards

**Comment by logaretm** [comment]
In your example the schema is not reactive, so you need to make it a computed schema since you want the matching to change every time the other field changes.
