### ISSUE TITLE
Vue warns "inject() can only be used inside setup() or functional components." when trying to insert new object or array.

### ISSUE THREAD

**Issue by hironaokato** [formvuelate/formvuelate#248]
Hi there,  I'm using Vite and Vue3 written under Composition API style. (and Chrome as browser)

I'm facing a problem with adding new object or array in current schema. 
For example, the demo page 
https://codesandbox.io/s/fvl-playground-3x-ojbt9?from-embed
or 
https://codesandbox.io/s/fvl-useschemaform-3x-w7i2f?from-embed

When you trying to add something into object or array into schema, Vue tells "inject() can only be used inside set()...". 

My understanding is the schema is ref/reactive and there should be no problem.

I'm reading the guide page and cannot solve this issue so far, so please let me know if there's proper way to do it.

Best

**Comment by marina-mosti** [comment]
I'm not sure I understand, can you provide some code examples?

**Comment by hironaokato** [comment]
Hi!

sure, but this demo code provides same issue 
https://codesandbox.io/s/fvl-useschemaform-3x-w7i2f?from-embed=&file=/src/main.js

when you open console on browser and click the "Are you a Vue fan?" checkbox, the console shows you the warning

index.js:27 [Vue warn]: inject() can only be used inside setup() or functional components. 
  at <SchemaForm schema= {firstName: {…}, lastName: {…}, email: {…}, favoriteThingAboutVue: {…}, isVueFan: {…}, …} > 


My code is copy and pasted from the demo too

**Comment by marina-mosti** [comment]
Ok I see it now, thank you
