### ISSUE TITLE
Using local imports with Vee Validate plugin does not render form

### ISSUE THREAD

**Issue by wesratcliff** [formvuelate/formvuelate#253]
**Describe the bug**
When using local imports along with the vee-validate plugin, the form does not render. Removing vee-validate allows it to render.

I've setup a sandbox below that allows the vee-validate plugin to be toggled on and off.

**To Reproduce**
- Visit: https://codesandbox.io/s/fvl-local-imports-with-validation-3o2e4?file=/src/App.vue
- Change line 18 from `false` to `true` (form will disappear)

**Expected behavior**
The form should render with or without the vee-validate plugin

**System Info**
- FormVueLate version: 3.7.1
- Vee Validate Plugin version: 3.7.1
- Vee Validate version: 4.5.5

**Comment by marina-mosti** [comment]
@logaretm there's a small chance this is fixed by #254 
I wonder if the lack of a default value was making noise and preventing the provide

**Comment by logaretm** [comment]
@marina-mosti yes the default value will silence the `inject` warning.

**Comment by logaretm** [comment]
@marina-mosti It doesn't seem like #254 fixes this. The reproduction uses the vee-validate plugin without the look-up.
