### ISSUE TITLE
Code sandbox is broken

### ISSUE THREAD

**Issue by catherineluse** [formvuelate/formvuelate#277]
Many examples on this page aren't rendering https://formvuelate.js.org/examples/#conditional-fields-with-schema

**Comment by marina-mosti** [comment]
Yeah, code sandbox has been hit or miss lately. I think they work if you open them in full screen. I think eventually we have to move to vuepress next or something that allows us to embed Vue 3 directly and whip up our own solution to examples.
Thanks for letting me know :)
