### ISSUE TITLE
How to trigger validate manually?

### ISSUE THREAD

**Issue by xiaok** [formvuelate/formvuelate#280]
Hi
In my app, clicking "confirm" button will pop up a modal to let the customer confirm whether the input is correct. Then click "submit" in modal to submit the form.
 I want to trigger validatation manually when user click "confirm" button, how can I do it?

https://formvuelate.js.org/guide/vuelidate.html#installation I read the document and didn't got the answer.

**Comment by marina-mosti** [comment]
Hey @xiaok the Vuelidate plugin is in pre-release state as shown on the top of the page, and frankly I wouldnt use it all. We may have to remove it completely from the docs at this point, since we haven't been able to put in any work on it. I recommend you check out our Vee-validate plugin, which is fully working

**Comment by xiaok** [comment]
@marina-mosti Actually I am using Vee-validate plugin.
Could you tell me is there any way to use Vee-validate or formvuelate to trigger validate for all fields?
I need some thing like form.validate() to validate all fields instead of submitting the form.

**Comment by davidzwa** [comment]
@marina-mosti I share a similar wish: I would like to be able to check the form validation outside the afterForm and beforeForm templates. This is quite common in order to share state to f.e. Dialog action buttons or nested components with internal forms.

**Comment by xiaok** [comment]
@davidzwa I made a small batch for this requirement: https://github.com/xiaok/formvuelate/commit/39d557c86ef9f33e7afbcc4fc71594b23deeeeac

**Comment by xiaok** [comment]
@davidzwa sorry I remove /src from .gitignore, please check this file https://github.com/xiaok/formvuelate/commit/39d557c86ef9f33e7afbcc4fc71594b23deeeeac#diff-fa0632017b6760c90600c2ea3973db6ebfbe269ac16b16a4f23945513aebecba

**Comment by davidzwa** [comment]
Went for a ref on the form and hacked myself out that way using watch/data. I will await the repo author's further steps. 

Thanks tho!
