### ISSUE TITLE
Unable to set validation for vee-validate

### ISSUE THREAD

**Issue by kokhoor** [formvuelate/formvuelate#283]
**Describe the bug**
As I would like to use vue-tel-input (which does its own validation and fire a callback when validation is done, I wanted to set the meta to validated and valid to true but validation will still run

**To Reproduce**
in a control, even with following set, the validation will still be executed, regardless of whether I set valid is true / false

````
<template>
    <input
      @input="update($event.target.value)"
</template>

<script setup>
function update(value) {
  props.validation.errorMessage = ''
  props.validation.errors = []
  props.validation.meta.valid = true
  props.validation.meta.validated = true
  emit('update:modelValue', value)
}
</script>
````

**Expected behavior**
Validation will not proceed when validated is true and the correct error message(s) populated to validation.errors

**System Info**
- FormVueLate version: 3.8.1
- plugins being used with versions: @formvuelate/plugin-vee-validate: ^3.8.1

**Additional context**
-

**Comment by marina-mosti** [comment]
Hey, you're mutating props which is a problem. I also don't know this lib and this is an integration that is not supported, maybe open an issue with them directly and ask them for advice

**Comment by kokhoor** [comment]
For anyone facing same issue, the solution I use is to define following handler @validate="onValidChanged" in VueTelInput, to return an empty string when the phone number is not valid yet. Is not like the perfect solution, but it does works (and maybe need to add a different validator to show different error message):

````
<script setup>
...
const v = ref(props.modelValue)
const mobile_number_valid = ref('')
function onValidChanged(event) {
  if (event) {
    mobile_number_valid.value = event.valid === true
    emit('update:modelValue', event.valid ? v.value : '')
  }
}
...
</script>
````
