### ISSUE TITLE
Add custom class for each schema-row

### ISSUE THREAD

**Issue by 4KDA** [formvuelate/formvuelate#290]
The ability to add custom classes for each schema-row element would greatly simplify the creation of adaptive forms of any complexity.

Add, please

**Comment by marina-mosti** [comment]
Can you provide a use case for what you're trying to achieve? Preferably with some code example of component and use

**Comment by 4KDA** [comment]
For example, here is the visual structure of the form
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/38465364/167132463-d2d4d06b-a360-471c-8f16-cdef1d1f777c.png">

**Comment by marina-mosti** [comment]
Seems like this is fixable with reading the docs here https://formvuelate.js.org/guide/schema-form.html#schemarowclasses

**Comment by 4KDA** [comment]
> Похоже, это можно исправить, прочитав документы здесь [https://formvuelate.js.org/guide/schema-form.html#schemarowclasses .](https://formvuelate.js.org/guide/schema-form.html#schemarowclasses)


I studied the documentation, but the schemaRowClasses property adds a class to all elements, and I need the ability to individually set classes for each field wrapper

**Comment by 4KDA** [comment]
> Seems like this is fixable with reading the docs here https://formvuelate.js.org/guide/schema-form.html#schemarowclasses


I studied the documentation, but the schemaRowClasses property adds a class to all elements, and I need the ability to individually set classes for each field wrapper

**Comment by 4KDA** [comment]
I need to get it like this

<img width="504" alt="image" src="https://user-images.githubusercontent.com/38465364/167135283-e8d8faca-8ca6-4703-9a4a-121603edb9c7.png">

**Comment by 4KDA** [comment]
@marina-mosti can you help?

**Comment by marina-mosti** [comment]
That's not possible as far as I remember. Try passing the class as part of the schema tree and it should try to merge. If it doesn't , then maybe open a pr 😊
