### ISSUE TITLE
Unable to get it running basic example, files missing

### ISSUE THREAD

**Issue by scramatte** [formvuelate/formvuelate#97]
Hello,

I'm unable to get it running basic example as some files are missing.
Can you provide following files and example to use into an existing vue project.

import OutputDisplay from './OutputDisplay'
import FormText from './form-elements/FormText'
import FormSelect from './form-elements/FormSelect'
import FormCheckbox from './form-elements/FormCheckbox'

Thank you

**Comment by marina-mosti** [comment]
Hello, @scramatte 

The components used in the examples are only for example purposes. FormVueLatte does not provide form components as it is not a component library, but it enables you to use your own :)

If you need some base components I recommend you check out Vuetify or some similiar component library.

**Comment by scramatte** [comment]
This is what I've done, I've followed you Blog post  and I make my component for bootstrap-vue. I was unable to get vulidate working so I've tried  your blog
https://www.vuemastery.com/blog/Validating-Schema-Driven-forms-with-Vuelidate/ and it works fine.

**Comment by marina-mosti** [comment]
I'm glad it worked for you! Going to close the issue as it is not related to the lib
