### ISSUE TITLE
Documentation: How to use Vuelidate with Formvuelatte

### ISSUE THREAD

**Issue by scramatte** [formvuelate/formvuelate#98]
Hello,

How can I use Vuelidate with Formvuelatte?
Can you add some doc about this?

Regards

**Comment by marina-mosti** [comment]
Hello @scramatte 
Currently integration with the two libraries is fairly complicated, and not officially supported. 

We are working on version 2.0 which will provide this capability as well as accompanying documentation. This version should be released shortly after Vue 3.0 is released officially. Keep posted :)

**Comment by scramatte** [comment]
Hello.

But it will still compatible with Vue 2 ? Any timeline ?
I've going to port our ERP to Vue2 + Laravel and I've got many many forms ...

Regards

**Comment by marina-mosti** [comment]
Version 2.0 uses a lot of features only available with Vue 3, so 2.0+ will only be compatible with Vue 3.0.

You can still use the current version for your Vue 2 projects, it will not be removed or unpublished - as is. There is not further work being planned with the current version.

We are working on some heavy changes to Vuelidate and FormVueLatte internals to make the seamless compatibility possible, which is not something easily done with the libraries in their current state.
